Fix unfriendly error when using non-string values as parameters
SomeoneWeird/cirrus pull request #22
Opened 2016-11-02 14:28 UTC by mirdhyn

2016-11-02 14:35 UTC, SomeoneWeird commented on src/utils.js
> +      if (typeof(value) != "string") {
nit: use `!==`

2016-11-02 14:36 UTC, SomeoneWeird requested changes
Awesome, appreciate this!

2016-11-02 14:45 UTC, mirdhyn commented on src/utils.js
> +      if (typeof(value) != "string") {
fixed

2016-11-07 09:09 UTC, SomeoneWeird approved these changes

2016-11-07 09:11 UTC, merged